add_test( [==[Factorial calculations]==] C:/msys64/ucrt64/home/julian/CppProjects/AlgoritmiaCombinatoria/build_gcc_debug_cpp17/tests.exe [==[Factorial calculations]==]  )
set_tests_properties( [==[Factorial calculations]==] PROPERTIES WORKING_DIRECTORY C:/msys64/ucrt64/home/julian/CppProjects/AlgoritmiaCombinatoria/build_gcc_debug_cpp17)
add_test( [==[Combination calculations]==] C:/msys64/ucrt64/home/julian/CppProjects/AlgoritmiaCombinatoria/build_gcc_debug_cpp17/tests.exe [==[Combination calculations]==]  )
set_tests_properties( [==[Combination calculations]==] PROPERTIES WORKING_DIRECTORY C:/msys64/ucrt64/home/julian/CppProjects/AlgoritmiaCombinatoria/build_gcc_debug_cpp17)
add_test( [==[Permutation calculations]==] C:/msys64/ucrt64/home/julian/CppProjects/AlgoritmiaCombinatoria/build_gcc_debug_cpp17/tests.exe [==[Permutation calculations]==]  )
set_tests_properties( [==[Permutation calculations]==] PROPERTIES WORKING_DIRECTORY C:/msys64/ucrt64/home/julian/CppProjects/AlgoritmiaCombinatoria/build_gcc_debug_cpp17)
add_test( [==[Fibonacci sequence]==] C:/msys64/ucrt64/home/julian/CppProjects/AlgoritmiaCombinatoria/build_gcc_debug_cpp17/tests.exe [==[Fibonacci sequence]==]  )
set_tests_properties( [==[Fibonacci sequence]==] PROPERTIES WORKING_DIRECTORY C:/msys64/ucrt64/home/julian/CppProjects/AlgoritmiaCombinatoria/build_gcc_debug_cpp17)
add_test( [==[Catalan numbers]==] C:/msys64/ucrt64/home/julian/CppProjects/AlgoritmiaCombinatoria/build_gcc_debug_cpp17/tests.exe [==[Catalan numbers]==]  )
set_tests_properties( [==[Catalan numbers]==] PROPERTIES WORKING_DIRECTORY C:/msys64/ucrt64/home/julian/CppProjects/AlgoritmiaCombinatoria/build_gcc_debug_cpp17)
add_test( [==[Generate permutations]==] C:/msys64/ucrt64/home/julian/CppProjects/AlgoritmiaCombinatoria/build_gcc_debug_cpp17/tests.exe [==[Generate permutations]==]  )
set_tests_properties( [==[Generate permutations]==] PROPERTIES WORKING_DIRECTORY C:/msys64/ucrt64/home/julian/CppProjects/AlgoritmiaCombinatoria/build_gcc_debug_cpp17)
add_test( [==[Generate combinations]==] C:/msys64/ucrt64/home/julian/CppProjects/AlgoritmiaCombinatoria/build_gcc_debug_cpp17/tests.exe [==[Generate combinations]==]  )
set_tests_properties( [==[Generate combinations]==] PROPERTIES WORKING_DIRECTORY C:/msys64/ucrt64/home/julian/CppProjects/AlgoritmiaCombinatoria/build_gcc_debug_cpp17)
add_test( [==[Rational binomial coefficients]==] C:/msys64/ucrt64/home/julian/CppProjects/AlgoritmiaCombinatoria/build_gcc_debug_cpp17/tests.exe [==[Rational binomial coefficients]==]  )
set_tests_properties( [==[Rational binomial coefficients]==] PROPERTIES WORKING_DIRECTORY C:/msys64/ucrt64/home/julian/CppProjects/AlgoritmiaCombinatoria/build_gcc_debug_cpp17)
add_test( [==[BigInt operations]==] C:/msys64/ucrt64/home/julian/CppProjects/AlgoritmiaCombinatoria/build_gcc_debug_cpp17/tests.exe [==[BigInt operations]==]  )
set_tests_properties( [==[BigInt operations]==] PROPERTIES WORKING_DIRECTORY C:/msys64/ucrt64/home/julian/CppProjects/AlgoritmiaCombinatoria/build_gcc_debug_cpp17)
set( tests_TESTS [==[Factorial calculations]==] [==[Combination calculations]==] [==[Permutation calculations]==] [==[Fibonacci sequence]==] [==[Catalan numbers]==] [==[Generate permutations]==] [==[Generate combinations]==] [==[Rational binomial coefficients]==] [==[BigInt operations]==])
